name: caytoo

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: caytoo_PostgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: caytoodatabase
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: caytoo_Redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
