name: caytoo

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: caytoo_PostgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: caytoodatabase
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgresdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: caytoo_Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  news-worker:
    build:
      context: ./news-worker
    container_name: caytoo_NewsWorker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    # volumes:
    #   - ./news-worker:/app
    #   - /app/node_modules  # Uncomment for development to avoid overwriting node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  engine:
    build:
      context: ./engine
    container_name: caytoo_Engine
    command: go run cmd/engine/main.go
    volumes:
      - ./engine:/app
    depends_on:
      redis:
        condition: service_healthy
      news-worker:
        condition: service_started

  db-processor:
    build:
      context: ./db-processor
    container_name: caytoo_DBProcessor
    command: sh -c "npx prisma migrate deploy && npm run dev"
    ports:
      - "3001:3001"
      - "5555:5555" # For Prisma Studio
    environment:
      DATABASE_URL: "postgresql://admin:caytoodatabase@db:5432/postgresdb"
    # volumes:
    #   - ./db-processor:/app
    #   - /app/node_modules  # Uncomment for development to avoid overwriting node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      engine:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    container_name: caytoo_Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      db-processor:
        condition: service_started
      news-worker:
        condition: service_started
      engine:
        condition: service_started

volumes:
  db_data:
  redis_data:
